"""Added events table

Revision ID: 30517d831295
Revises: 81de8d3267e6
Create Date: 2022-11-09 18:42:29.589135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30517d831295'
down_revision = '81de8d3267e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('eventtype', sa.String(length=20), nullable=True),
    sa.Column('olympic_id', sa.String(length=7), nullable=True),
    sa.Column('is_team_event', sa.Boolean(), nullable=True),
    sa.Column('num_players_in_team', sa.Integer(), nullable=True),
    sa.Column('result_noted_in', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['olympic_id'], ['olympics.olympic_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
