"""Added olympics table

Revision ID: 732f374d616e
Revises: d08196193bb5
Create Date: 2022-11-09 17:05:47.592619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732f374d616e'
down_revision = 'd08196193bb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olympics',
    sa.Column('olympic_id', sa.String(length=7), nullable=False),
    sa.Column('country_id', sa.String(length=3), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('enddate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('olympic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('olympics')
    # ### end Alembic commands ###
