"""Added players table

Revision ID: 81de8d3267e6
Revises: 2ea177da2d70
Create Date: 2022-11-09 18:35:37.855087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81de8d3267e6'
down_revision = '732f374d616e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('player_id', sa.String(length=10), nullable=False),
    sa.Column('country_id', sa.String(length=3), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
